#!/bin/bash
# DESC: Build harvester binaries
set -e

# Source version variables
. ./harvester-env.sh

mkdir -p bin

version=${HARVESTER_VERSION}
commit=${HARVESTER_COMMIT}
commit_tag=${HARVESTER_COMMIT_TAG}
commit_branch=${HARVESTER_COMMIT_BRANCH}
arch=${HARVESTER_ARCH}

# add coverage flags if there is no tag and it's on master or a version branch like v1.3
if [[ "$commit_tag" == "" ]] && [[ "$commit_branch" == "master" || "$commit_branch" =~ ^v[0-9]+\.[0-9]+$ ]]; then
    COVERPKG="-coverpkg=github.com/harvester/harvester/..."
    COVER_FLAGS="-cover $COVERPKG"
fi

OTHER_LINKFLAGS="-extldflags -static -s"
LINKFLAGS="-X github.com/harvester/harvester/pkg/version.Version=${version}
           -X github.com/harvester/harvester/pkg/version.GitCommit=${commit}
           -X github.com/harvester/harvester/pkg/settings.InjectDefaults=${DEFAULT_VALUES}"

build_binary () {
    local BINARY="$1"
    local PKG_PATH="$2"
    local ENABLE_CROSS="${3:-false}"

    echo "Building ${BINARY}..."

    CGO_ENABLED=0 go build -o "bin/${BINARY}" -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" $COVER_FLAGS "${PKG_PATH}"
    if [ "$CROSS" = "true" ] && [ "$arch" = "amd64" ] && [ "$ENABLE_CROSS" = "true" ]; then
        GOOS=darwin go build -ldflags "$LINKFLAGS"  -o "bin/${BINARY}-darwin" "${PKG_PATH}"
        GOOS=windows go build -ldflags "$LINKFLAGS" -o "bin/${BINARY}-windows" "${PKG_PATH}"
    fi
}


build_binary "harvester" "." "true"
build_binary "harvester-webhook" "./cmd/webhook"
build_binary "upgrade-helper" "./cmd/upgradehelper"

