#!/bin/bash
# DESC: Runs the unit tests
set -ex

# The root of the harvester directory
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"

# Source version variables
. ./mk-env.sh

exit 0
export PRELOADING_IMAGES="rancher/harvester-webhook:${HARVESTER_TAG}"
export WEBHOOK_IMAGE_NAME="rancher/harvester-webhook:${HARVESTER_TAG}"

echo "Running integration tests"
CGO_ENABLED=0 ginkgo -r -v -trace -tags=test \
	      -fail-fast -slow-spec-threshold=2m -timeout=30m  "${ROOT_DIR}/tests/integration/..."
