#!/bin/bash
set -e

CONTAINER_WORKDIR="$1"
DOCKER_PROGRESS="${2:-auto}"

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)

docker build \
    --progress="$DOCKER_PROGRESS" \
    -f "$SCRIPT_DIR/Dockerfile" \
    -t harvester-integration-test:latest \
    "$ROOT"

docker run --rm -it \
    --privileged \
    --network host \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v harvester-integration-test-cache:${CONTAINER_WORKDIR}/.cache/go-build \
    harvester-integration-test:latest \
    bash mk/test-integration/build
