#!/bin/bash
set -e

BIN_IMAGE="$1"
CONTAINER_WORKDIR="$2"
DOCKER_PROGRESS="${3:-auto}"

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)

source "$SCRIPT_DIR/../lib.sh"

docker build \
    --progress="$DOCKER_PROGRESS" \
    -f "$SCRIPT_DIR/Dockerfile" \
    -t "$BIN_IMAGE" \
    "$ROOT"

extract_binary "$BIN_IMAGE" "$CONTAINER_WORKDIR/bin/harvester-installer" "$ROOT/bin/harvester-installer" "harvester-installer-bin-extract"
