#!/bin/bash
set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

source "$SCRIPT_DIR/../lib.sh"

set_mk_docker_build_args
MK_DOCKER_BUILD_ARGS+=(--build-arg MK_ADDONS_IMAGE)

docker build "${MK_DOCKER_BUILD_ARGS[@]}" \
    -f "$SCRIPT_DIR/Dockerfile" \
    -t "$MK_INSTALLER_BIN_IMAGE" \
    "$MK_ROOT"

extract_binary "$MK_INSTALLER_BIN_IMAGE" "$MK_CONTAINER_WORKDIR/bin/harvester-installer" "$MK_ROOT/bin/harvester-installer" "harvester-installer-bin-extract"
