#!/bin/bash
set -e

# Arguments passed from Makefile
MK_DIR="$1"
ROOT="$2"
BIN_IMAGE="$3"
CONTAINER_WORKDIR="$4"
DOCKER_PROGRESS="${5:-auto}"

# Source shared library functions
source "$MK_DIR/lib.sh"

docker build \
    --progress="$DOCKER_PROGRESS" \
    -f "$MK_DIR/build-installer/Dockerfile" \
    -t "$BIN_IMAGE" \
    "$ROOT"

extract_binary "$BIN_IMAGE" "$CONTAINER_WORKDIR/bin/harvester-installer" "$ROOT/bin/harvester-installer" "harvester-installer-bin-extract"
