#!/bin/bash -xe

HARVESTER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"

# build installer binary first, upgrade image need it
cd ${HARVESTER_DIR}/installer/scripts
./build

# harvester backend and main images
cd ${HARVESTER_DIR}/scripts

./build
./package-webhook
./package-upgrade
./package


# package ISO
cd ${HARVESTER_DIR}/installer/scripts
./check-images
# ./test
./build-bundle
./package-harvester-repo
./package-harvester-os
