#!/bin/bash
set -e

INSTALLER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
HARVESTER_DIR="$( cd "${INSTALLER_DIR}/.." &> /dev/null && pwd )"
cd $INSTALLER_DIR

INSTALLER_SCRIPT_DIR="${INSTALLER_DIR}/scripts"
source ${INSTALLER_SCRIPT_DIR}/lib/addon

addons_path=${HARVESTER_DIR}/../addons
load_and_source_addon ${addons_path} https://github.com/harvester/addons.git main

generate_addon ${addons_path}
# copy the generated addon yamls to installer
cp ${addons_path}/*.yaml ./pkg/config/templates

echo "All existing template files"
ls -alth ${INSTALLER_DIR}/pkg/config/templates
echo "The templated rancherd-22-addons.yaml file"
cat ${INSTALLER_DIR}/pkg/config/templates/rancherd-22-addons.yaml

cd ${HARVESTER_DIR}

echo "Running installer tests"
go test -cover -tags=test ./installer/pkg/...
