#!/bin/bash
set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source "$SCRIPT_DIR/../lib.sh"

set_mk_docker_build_args

docker build "${MK_DOCKER_BUILD_ARGS[@]}" \
    -f "$SCRIPT_DIR/Dockerfile" \
    "$MK_ROOT"
