#!/bin/bash
set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)

docker build \
    --progress="$MK_DOCKER_PROGRESS" \
    --build-arg MK_CONTAINER_WORKDIR \
    -f "$SCRIPT_DIR/Dockerfile" \
    "$ROOT"
